/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: 8sianDude (https://sketchfab.com/haoliu95)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/mossberg-590-mariner-dc5b2d69587344229b60b1a7dbe07a81
Title: Mossberg 590 Mariner
*/
"use client";
import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { useFrame } from "@react-three/fiber";

const Shotgun = React.memo(function Shotgun(props) {
    // Use React.memo for performance optimization
    const { nodes, materials } = useGLTF("/models/Shotgun-transformed.glb");
    const modelRef = useRef();
  
    useFrame(() => {
      modelRef.current.rotation.y += 0.02;
    });

  return (
    <group {...props} 
    dispose={null}
    scale={[0.5, 0.5, 0.5]}
    position={[0.0, 0.5, 0]}
    ref={modelRef}
    >
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.m590_receiver_m590_receiver_0.geometry}
        material={materials.m590_receiver}
        // rotation={[0, 0, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.m590_receiver_m590_furniture_0.geometry}
        material={materials.m590_furniture}
        // rotation={[0, 0, 0]}
      />
    </group>
  )
})

export default Shotgun;
useGLTF.preload('/Shotgun-transformed.glb')